### PR TITLE
WIP: adding azure blob as object store

### LINKED ISSUE #687: add azure blobstore support as object store backend

### PR DESCRIPTION
**Pull request by piyushsingariya**
Fixes #687 .

### Description

This PR aims to add support for Azure Blob Storage as Object Store in parseable.

The Solution/Changes implemented in this PR are as follows:
- Add a separate CLI subcommand similar to `s3-store`
- Add Config/Vars required to connect to Azure Blob Storage
- Alter + Rename previously written S3 struct into a generic struct to use LimitStore better and to enable re-usability of code for Azure Blob as well.

> [!NOTE]  
> I've only started learning Rust less than a week ago, so I am unfamiliar with Rust ecosystem. Any guidance or feedback would be greatly appreciated as I work on this task.

<hr>

This PR has:
- [ ] been tested to ensure log ingestion and log query works.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by piyushsingariya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nikhilsinhaparseable** [comment]
@piyushsingariya for this to work, you need to implement all the methods defined under trait ObjectStorage
currently you will find two implementations for this trait (one for s3-store, other for local-store) - 
1. https://github.com/parseablehq/parseable/blob/main/server/src/storage/s3.rs
2. https://github.com/parseablehq/parseable/blob/main/server/src/storage/localfs.rs

**Comment by piyushsingariya** [comment]
Hi @nikhilsinhaparseable, 
I've reutilized the pre-written implementation for ObjectStorage of S3, since S3 is initializing cloud client with `LimitStore<AmazonS3>` as `LimitStore<ObjectStore>`, I've avoided re-implementing and reuse the same code for AzureBlob via initialzing an instance of `LimitStore<MicrosoftAzure>` as `LimitStore<ObjectStore>`.

I've achieved this via altering the previous S3 struct to be generic and to accept anything that implements the trait `ObjectStore`  from object_store crate.

**Comment by piyushsingariya** [comment]
@nikhilsinhaparseable It would be easier if you could checkout my pr in local with `gh cli`, that way it would be easier in understanding how we don't need to rewrite the implementation.

Do let me know what else needs to be fixed here, since I am really looking forward to getting this PR merged.

**Comment by nitisht** [comment]
@piyushsingariya we had a customer waiting for this so @nikhilsinhaparseable had to work on this here #955 . This effort looks like will take more time. I'd request you to close this PR.

**Comment by piyushsingariya** [comment]
I'm quite disheartened by how this has turned out. I spent a few days working on my PR, hoping to contribute meaningfully, it sat unreviewed for a week. 

Though I understand the priority shift and urgency but this feels highly discouraging and doesn't align with the open-source spirit of collaboration. I truly hope this isn't indicative of how external contributions are generally handled.

I hope this feedback helps improve the process for other contributors. Closing this PR.

**Comment by nitisht** [comment]
Thanks @piyushsingariya

**Pull request closed without merging**
