### PR TITLE
Increase the request body payload size limit to 10MB (#271)

### LINKED ISSUE #271: Increase the request body payload size limit to 10MB

### PR DESCRIPTION
**Pull request by regularcoder**
Fixes #271.

### Description
Increase the request body payload size limit to 10MB

### CODE REVIEW

**Comment by nitisht** [comment]
@trueleo PTAL

**Comment by trueleo** [comment]
@nitisht This increases the payload size to ~10mb. However just took a look and it seems like the limit is changes just for logstream service but not for ingest endpoint

**Review by trueleo — APPROVED** [review]

**Comment by regularcoder** [comment]
Thank you @trueleo for reviewing. So @nitisht  it seems logical to also add the limit to /ingest endpoint? After all it seems to serve same purpose.

Also - please let me know if I should go ahead and fix the "warning: variables can be used directly in the `format!` string" Clippy errors that are unrelated to my change.

**Comment by trueleo** [comment]
@regularcoder Yes, /ingest endpoint serves the same purpose as /logstream/{stream_name}. You can put the same JsonConfig to [/ingest](https://github.com/parseablehq/parseable/blob/main/server/src/main.rs#L264) as well

**Comment by nitisht** [comment]
Thanks for the PR @regularcoder please proceed with the `ingest` changes as well. We can then merge this. You can ignore the clippy failure.

**Pull request merged**
