### PR TITLE
Impl Arrow Flight Protocol for Querying

### PR DESCRIPTION
**Pull request by Eshanatnight**
Fixes #.

### Description

Impl Arrow Flight Protocol for Querying

<hr>

This PR has:
- [x] been tested to ensure log ingestion and log query works.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by Eshanatnight** [comment]
Move Diverging changes to a separate branch. Merge later

**Comment by Eshanatnight** [comment]
Query is working with Staging Data.

Edge case, if the staging query is triggered right at the moment object store sync takes place,
the staging data is coming twice. If the we query give or take 5 seconds later it works as intended

**Comment by Eshanatnight** [comment]
Should fix #735

**Review by nikhilsinhaparseable — APPROVED** [review]
looks good to merge

**Pull request merged**
