### PR TITLE
switched to tokio tasks

### LINKED ISSUE #652: Use tokio async runtime instead of std::thread
Update the architecture to use tokio tasks instead of threads

[Tokio Docs](https://docs.rs/tokio/latest/tokio/task/index.html)

Edit: add documentation link

### PR DESCRIPTION
**Pull request by vishalkrishnads**
Fixes #652.

### Description

* Rewrote `object_store_sync()` & `run_local_sync()` in server's sync.rs to use tokio tasks but with same function signature. Updated the invoking code to match.

* Rewrote `init_scheduler()` in server's storage/retention.rs to use tokio tasks but with same function signature. Updated the invoking code to match.

<hr>

This PR has:
- [X] been tested to ensure log ingestion and log query works.
- [X] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by vishalkrishnads** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nitisht** [comment]
@vishalkrishnads are you able to verify if the server is running and accepting events after this change?

**Comment by vishalkrishnads** [comment]
the server runs but isn't accepting requests.

**Comment by nitisht** [comment]
> the server runs but isn't accepting requests.

I see, so thats why tests are failing. Would you take a deeper look at what is going on?

**Comment by vishalkrishnads** [comment]
yes sure, i'll look into it

**Comment by nitisht** [comment]
> yes sure, i'll look into it. please give me a bit more time.

Sure @vishalkrishnads . Please let us know if you need any help.

**Comment by vishalkrishnads** [comment]
hey thanks! i'm running into this error

```
quest-1      | 2024/08/03 06:28:40 INFO ingested logs, sleeping... iteration=2 log_count=100                                                                       
quest-1      | 2024/08/03 06:29:40 INFO downloading parquet files from MinIO bucket=parseable stream=ccbvdvdzpm                                                    
quest-1      | 2024/08/03 06:29:40 INFO skipping path, not a parquet file key=ccbvdvdzpm/.stream/.schema
quest-1      | 2024/08/03 06:29:40 INFO skipping path, not a parquet file key=ccbvdvdzpm/.stream/.stream.json
quest-1      | 2024/08/03 06:29:40 INFO skipping path, not a parquet file key="ccbvdvdzpm/date=2024-08-03/manifest.json"                                           
quest-1      | 2024/08/03 06:29:40 INFO downloaded files paths="[ccbvdvdzpm.date=2024-08-03.hour=06.minute=27.d8fab79aca10.data.NMTjYDBx7y4ZJwP.parquet]"          
quest-1      | 2024/08/03 06:29:40 INFO loading flogs from parquet files paths="[ccbvdvdzpm.date=2024-08-03.hour=06.minute=27.d8fab79aca10.data.NMTjYDBx7y4ZJwP.parquet]" count=1                                                                                                                                                     
quest-1      | 2024/08/03 06:29:40 INFO reading parquet file path="ccbvdvdzpm.date=2024-08-03.hour=06.minute=27.d8fab79aca10.data.NMTjYDBx7y4ZJwP.parquet"
quest-1      | --- FAIL: TestIntegrity (120.14s)
quest-1      | panic: runtime error: index out of range [-1] [recovered]                                                                                           
quest-1      |  panic: runtime error: index out of range [-1]                                                                                                      
quest-1      | 2024/08/03 06:29:40 INFO loading flogs from parquet files paths="[ccbvdvdzpm.date=2024-08-03.hour=06.minute=27.d8fab79aca10.data.NMTjYDBx7y4ZJwP.parquet]" count=1
```

But I'm not able to find the issue. Is it because the new changes alter the timing sync as said [here](https://github.com/parseablehq/quest/blob/f1cfd68e4c88f801b49de9086c70f25eedf6612f/integrity_test.go#L91)?

**Comment by vishalkrishnads** [comment]
this is kind of confusing. in [this commit](https://github.com/parseablehq/parseable/pull/862/commits/0f8d4ad8b3d9b8ee2d1d87f26aa19c90730810c6), all checks except the indentation one were passing. however, as I [corrected it](https://github.com/parseablehq/parseable/pull/862/commits/ac49651f5cba4d5b07b9e0b2f5c7cf4eb6705c96), the distributed docker compose test started failing. @nitisht any help would be appreciated.

**Pull request merged**
