### PR TITLE
Solves issue #976 (added working link in place of page not found link) 

### LINKED ISSUE #976: page not found - (link error) in README.md
When I click on this link in README.md- LLM integration ↗︎](https://www.parseable.io/docs/llm) - page not found shows up
I have raised PR which solves this issue... checkout

image

Screenshot 2024-10-26 193801

### PR DESCRIPTION
**Pull request by negativenagesh**
Fixes #976

### Description

This PR adds working link as mentioned in issue #976, below page opens up when clicked on this link https://www.parseable.io/docs/llm in README.md

image

<hr>

This PR has:
- [x] been tested to ensure log ingestion and log query works.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks @negativenagesh can you add this comment 

```
I have read the CLA Document and I hereby sign the CLA
```

**Comment by negativenagesh** [comment]
Hi, @nitisht, We met today at Microsoft, Bengaluru.

I have read the CLA Document and I hereby sign the CLA

**Comment by nitisht** [comment]
recheck

**Pull request merged**
