### PR TITLE
chore: multiple improvements

### PR DESCRIPTION
**Pull request by ByteBaker**
It's an overall negative PR, meaning there are more lines deleted than added. Following changes have been made, some of which should actually improve the performance all so slightly.

- remove a few `unwrap()`, partly covers #933
- replace code with idiomatic version of it
- rewrite `time_from_path` to make it simpler + robust
- rewrite `flatten_objects_for_count` reducing loops and simplify the accumulator inside it
- make the Regex in `Message::extract_column_names` static
- correct a few panic messages

### Description

<hr>

This PR has:
- [ ] been tested to ensure log ingestion and log query works.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added documentation for new or modified features or behaviors.

### CODE REVIEW

**Comment by ByteBaker** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ByteBaker** [comment]
recheck.

**Comment by ByteBaker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ByteBaker** [comment]
recheck

**Comment by nikhilsinhaparseable** [comment]
@ByteBaker Integration tests fail in the PR, and if you look in the details, Quest Integrity test fails as the ingestion fails with the error - 
`Error in response: Invalid(Schema mismatch)`
Clone the quest repo from https://github.com/parseablehq/quest
and run the Parseable server locally.
Execute the TestIntegrity function under integrity_test.go to reproduce the error.

Looks like there is some issue with the change you did in one of the two methods - 
`fields_mismatch` and `valid_type`

The same test runs successfully in the main branch, you can verify the same.

Thanks!

**Comment by nitisht** [comment]
Closing because of no response. @ByteBaker feel free to reopen if you plan to work on this.

**Pull request closed without merging**
